services:
  demo:
    container_name: demo
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo-db:5432/demo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - demo-db

  demo-db:
    container_name: demo-db
    image: postgres:latest
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
