
spring:
  datasource:
    username: postgres
    password: password
  cloud:
    gcp:
      sql:
        instance-connection-name: daniel-361210:europe-north1:demo-instance
        database-name: demo
  jpa:
    generate-ddl: true