
spring:
  datasource:
    username: postgres
    password: password
  cloud:
    gcp:
      sql:
        # This needs to be here for now, if not the cloud run instance won't be able to connect to the db
        # instance-connection-name:
        database-name: demo
  jpa:
    generate-ddl: true