
spring:
  datasource:
    username: postgres
    password: password
  cloud:
    gcp:
      sql:
        # We cannot instantiate the variable `instance-connection-name` when deploying because it takes precedence over env
        # variables passed through terraform for Cloud Run.
        database-name: demo
  jpa:
    generate-ddl: true