
name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SA_KEY: ${{ secrets.GCP_GITHUB_ACTIONS_SA_KEY }}
  IMAGE: demo-repo
  LOCATION: europe-north1

jobs:
  build:
      runs-on: ubuntu-latest
      environment: actions-dev

      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
        - name: Build and test with Maven
          run: mvn package
        # Build the Docker image
        - name: Build
          run: |-
            docker build \
              --tag "$LOCATION-docker.pkg.dev/$PROJECT_ID/$IMAGE/demo:$GITHUB_SHA" \
              --build-arg GITHUB_SHA="$GITHUB_SHA" \
              --build-arg GITHUB_REF="$GITHUB_REF" \
              .
        - name: Checkout
          uses: actions/checkout@v3

        # Setup gcloud CLI
        - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
          with:
            service_account_key: ${{ secrets.GCP_GITHUB_ACTIONS_SA_KEY }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}

        # Configure Docker to use the gcloud command-line tool as a credential
        # helper for authentication.
        # We need to use the specific region in order to authenticate properly.
        - run: |-
            gcloud --quiet auth configure-docker "$LOCATION-docker.pkg.dev"
        # Push the Docker image to Google Container Registry
        - name: Publish
          run: |-
            docker push "$LOCATION-docker.pkg.dev/$PROJECT_ID/$IMAGE/demo:$GITHUB_SHA"
