
name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn clean install
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag demo:$(date +%s)
